language: php

php:
  - 5.2
  - 5.3
  - 5.4

env:
  - DB=mysql

before_script:
  - composer install --prefer-dist --dev

install: php vendor/vendors.php
  
script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email: a.fiori@cheapnet.it