language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

# env: - DB=mysql

before_install:
  - composer self-update
  - composer install

before_script:
  - tests

script:
   - phpunit

notifications:
  email: a.fiori@cheapnet.it