language: php

php:
  - 5.4
  - 5.5

before_install:
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update
  - composer self-update
  - composer update
  - composer install --dev --no-interaction

before_script:
  - cd tests

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
 
notifications:
   email: a.fiori@cheapnet.it
