language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - composer self-update
  - composer update
  - composer install --dev

before_script:
  - cd tests

script:
   - phpunit

notifications:
  email: a.fiori@cheapnet.it